# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
        image: myapp/app
        ports:
            - '9001:9000'
        env_file:
            -   .env
        volumes:
            - './project:/var/www/html'

        networks:
            - app-network
        restart: always

    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        networks:
            - app-network

        volumes:
            - './project/storage/app/public:/var/www/html/storage/app/public'
        ports:
            - "443:443"
            - "80:80"
        restart: always
        depends_on:
            -   app

networks:
    app-network:
       driver: bridge
